### PR TITLE
add ts, fix some style problems

### PR DESCRIPTION
**Pull request by asukaminato0721**
convert to ts, `yarn preview` ,  `yarn build` success.

~~Please fix the ArchLinux mirror~~

### CODE REVIEW

**Comment by wenxuanjun** [comment]
Oops I've just finished part of the convention without noticing your PR. :sob:

Could you please re-apply your modifications based on the latest commit. I will be obliged if you would solve the conflicts ~~because I am new in TypeScript and both my code and my brain are in a mess.~~

By the way, the ArchLinux mirror is fixed with new mirror `debian-security` added.

**Comment by asukaminato0721** [comment]
actually there is an easy way: ~~force push to an early commit, then there will be no conflict~~ .

**Comment by asukaminato0721** [comment]
fixing conflict.

**Comment by asukaminato0721** [comment]
Just some comments.

According to the npm doc, https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file

> "dependencies": Packages required by your application in production.
> "devDependencies": Packages that are only needed for local development and testing.

The "@types/*" packages are not needed in production, so it's ok to put them into dev dependencies.

https://www.oreilly.com/library/view/effective-typescript/9781492053736/ch06.html

~~Actually, I did this.~~ , though it's not important.

**Comment by wenxuanjun** [comment]
Yes, it's totally right. Though putting them together won't break anything (our project is a SPA, not a module, so both packages in `dependencies` and `devDependencies` will always be installed when fetching dependences), it does conform to the rules specification, so I will do a complete division soon.

Moreover, the `react-material-you-theme` is planned to be added to our project. If you are interested you might want to submit a new PR, thanks for your contribution.

**Comment by wenxuanjun** [comment]
I gave up splitting these dependencies, reasons are below:
<https://github.com/facebook/create-react-app/issues/6180>
<https://github.com/facebook/create-react-app/issues/1764>

If you have any opinions or suggestions, feel free telling me so that we can make the project better, thanks.

**Pull request merged**
